service:
    name: blindbeez-backend-serverless-nest
plugins:
    - serverless-plugin-typescript
    - serverless-offline
provider:
    name: aws
    runtime: nodejs10.x
    timeout: 30
package:
    individually: true
    include:
        - ormconfig.json
functions:
    main:
        handler: src/lambda.handler
        # events: [{http: {method: any, path: '/{any+}', cors: true}}]
        events: 
            - http:
                path: companies
                method: get
                cors: true 